name: Build
on:
  push:
    branches:
      - master
jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2.3.4
           with:
              persist-credentials: false
              fetch-depth: 0
         - uses: webfactory/ssh-agent@v0.4.1
           with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
         - uses: cachix/install-nix-action@v12
           with:
              install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
              extra_nix_config:
                 experimental-features = nix-command flakes
         - run: |
            echo "PWD IS $PWD"
            nix build . -o site -L
            ls -a
            ls -a site/
         - uses: crazy-max/ghaction-github-pages@8f06ab4000fed6be5ff1fe113aca078422695daf
           if: success()
           with:
              verbose: true
              build_dir: site
              target_branch: pandoc
              keep_history: false
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
